travis:
  secure:
    BINSTAR_TOKEN: HR1iJd1DVkbSR9teMZc27o7yxD/XlPrOZKet6mbLdxfHTzscs5KJaQVWh2G6jU3NZS8ooZIcLYjMabaLq3HihsYedDgAUcCg5kOHR0tHeJx7R8MG0+K27/we5RihN1X9Sgl3BM4f5U17Moznl4slCE88Q95qk/H6/mprt+We068OXTKMlxXws7YQB+6LTTg7vtRqBHUqZtJdJoVhtdzFZ9W5O0BOUee+1WsZjnE90HawT7TDvznJ3za8WJSFLzpha6wdhW5wztxfFlVxOsMPJnjgapDbFF8Om7aaV6iWP8iqbgtDnOt8mT6lwB+jqdORHqYgUR3zUutHIE1JAHFa8GCRixz/FWFWlS7VwVIgsuhF6cHGWR49Gy9xpf6chZ1Xc3sXXrv8Be9JJabaxItzD4edgenddo5AO4DeNr0/Lct1p0CF867aW89LuU76QxnUXnNdwaNc/gUDr7I8e+T0ES5MjFh9TP1Ntaqjw0ORfh9lSxxf4QEhZDZV2zQy4DRYbdYCUGf/vI46S8b3Tmr2Fdz5qoyZJM9O+u+1+ecHW2uidBF5VVtb9gqsqdGyBtokrqSlCnI53D/rlEAHiUfZUl0lV+iL335MdW6RO4UsX3uLKz2lGRRk1mNQu33j76W8qdlexvbcYRHEFT+viuojeli6JtaF0XxNXyP7vtsewfw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
