travis:
  secure:
    BINSTAR_TOKEN: Xvvyd/vyhz/JmbMhxF4Zsm2R5cYjp0kxigPeyYD8TeRs7IpOQjzl9Bw49IJi3j/+Q83cf0Ex5QDDJeMxmkfdjuwh+6gfUXCwXz00cmi352RRwUtpOtrb5TbkPaviqpBvy5hIVr0BhThFw8jp0mphJVoMVo768ZBuXKle2+rJSbb+AZFAn5z6aHQ6tTsk9bFvD9agI6guSRKWEOAY0ftrzgovbzoV5fkLk9oHMkXiagqN+iTzZ5njPCmFo4qaB6LRPnRfSZbL5J3xy+dZIbuaQTBcUQfWpiC6//yKkwRvt77+Crdh6kUqDCKs4gsjBJGay5efcfEwCWBQPCIsnmNnRlldKJQfyC6rpYrbcLFs8H/umhBpAT9gS+EsD/R+1I7lAJ26Nu8ewV15a44UDsiqNHQU+PjUI+FpRllRSDTqdRCJbabb5TkLT1VuSjN3g49bIN/kUaI8x1H1jaDZAdh6+BuO7JucOlM6zBs3xlfeadEqHnhrJGbGikNwPQ6z8IoWTbxq99OczV6wCQFTJympH1lkgvxgpMX8dAJkPRZqJ9TyT3tB/SwzcvDqGA7XRiZETaPi4spCJIwutmaYnO9hp6+WjqvKSV2wDkN/G+5BC//B8EhwtOKl/Rda+GHvOvshmp04BwkNb6WYImTeZsFR2j3KQ2T5u3rFWgEbN/y2jWI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
