travis:
  secure:
    BINSTAR_TOKEN: aIkYqtR71dUxChb2nakJabArf6LF0cJGhA36jsY6IfF6dXjg5Hv7SrKOrTc60Ubklrc6vg7Jwcf4Fqup2B1G1Y/OaCZHFHuSEJWh4Y1hqOmaDLz0h4EZ3iy5caPL2RTNexpdnceHthnfZMnyif9jiTzj/LFME6lU9dj/tkh7tkH7R55r1LzAjK0rc+Z+DSgMuacXIeGiRipOmNoJFkhUZ8qrgNK7+/L5fpxI0k9i8VQbjvA3PUkUsClD28B9EAoxlsykWFOg4UKa1S4or7GTxQjfBMlI7DuYAI8ubt972Yk9n75v+bP2DRcNlYslwGiZrV6spNITlgOXcx/CcqYqYL4TZPSy+lnefCCDOyUTvwOcse3pd1XlmAm/Q08n3wyW3cJOTB3k7fCTUCRgrXhSLiLH7uGNVTCSxeyjvpYvw6LVB9oe6oKo6gqDPPTLkdIXwjw9tps0hpFw4Wrz2Q9NKYJaYv725ujzq1N4+MeKNhzuxmFMBcg0/8G9QVACbkjLAycoVwiAcEEM8eGKyzu8Xf/TSnQDq36S64dSVb01lKpE2E6uicA4QpdBAc7nPymGkRFweUW84G42HIoI3+IC6D6q9wK+FjR/DeW6d52+jG4HjEnhbQkUkY4cG8i1kB9ux/fL7qy11ucwO2FW0l5aMa6n7UjmhUR4POc5rtCF1HI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
